#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &

strong() {
    echo -n -e "\033[32;49;1m"
    echo $@
    echo -n -e "\033[39;49;0m"
}

RUNDIR=${OPENSHIFT_REPO_DIR}
MAKODIR=${OPENSHIFT_REPO_DIR}/mako
DBDIR=${OPENSHIFT_DATA_DIR}/db

strong "Generate mako.conf"
cat << EOF > ${MAKODIR}/mako.conf
port=$OPENSHIFT_DIY_PORT
host="$OPENSHIFT_DIY_IP"
apps={
    {
        name="", 
        path="$OPENSHIFT_REPO_DIR/diy"
    }
}
EOF

strong "Link data dir"
if [ ! -d "${DBDIR}" ]; then
    mkdir -p ${DBDIR}
fi
if [ ! -d "${MAKODIR}/data" ]; then
    ln -s $DBDIR ${MAKODIR}/data
fi

strong "Start MakoServer"
cd ${RUNDIR}
${MAKODIR}/mako -c ${MAKODIR}/mako.conf -d
